name:          前端编码规范
description:   开发灵活，稳定，可维护的 HTML, CSS 和 JavaScript 代码的规范
url:           http://johnsenzhou.github.io/code-guide/

markdown:      rdiscount
permalink:     pretty
pygments:      true
